# Taps
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "felixkratz/formulae"   # sketchybar / borders (Window Management)
tap "nikitabobko/tap"       # Aerospace (Window Management) 

# Formulae
## Developer tools
brew "neovim"
brew "tmux"
brew "starship"
brew "chezmoi"
brew "tmux-sessionizer"

## Desktop utilities
brew "felixkratz/formulae/borders"
brew "felixkratz/formulae/sketchybar", args: ["HEAD"]

# Casks
cask "ghostty"                      # Terminal
cask "helium-browser"               # Browser
cask "karabiner-elements"           # Keyboard remapping
cask "nikitabobko/tap/aerospace"    # Window management
cask "shortcat"                     # Keyboard-driven UI navigation

# Additional dependencies and tools
brew "git"
brew "ripgrep"          # Often used with Neovim
brew "fd"               # Neovim
brew "tree-sitter-cli"  # Neovim
brew "tree"             # Helpful for directory structure visualization
brew "grep"
brew "node"             # used for Pi
brew "fzf"              # Fuzzy finder for tmux scripts (swap-windows, sessionizer)
